### ISSUE TITLE
add twitter links for different countries

### ISSUE THREAD

**Issue by drtortoise** [CodeClub/codeclub-world#42]
add twitter links as well as websites?
![screen shot 2014-01-14 at 12 29 54](https://f.cloud.github.com/assets/201994/1910464/eb4a295e-7d17-11e3-9eda-a12b7b0aa29a.png)

**Comment by martinpeck** [comment]
Time passed. Issue got closed as part of legacy bug cleanup.
Adding twitter profile links makes sense, but it'll get picked up elsewhere (not in this version of the CCW site).
