### ISSUE TITLE
the list of languages is incomplete

### ISSUE THREAD

**Issue by drtortoise** [CodeClub/codeclub-world#43]

**Comment by martinpeck** [comment]
List of languages on CCW.org is a mess. We are missing some that we have official translations for, and we're showing some which we have only zip-file downloads of, but not official translations (i.e. no translated projects in one of the other GH repositories). Summary is...

On GitHub Pages site we have...
- Tiếng Việt (Vietnamese) - but it’s not mentioned on CCW site
- русский язык (Russian) - but it’s not mentioned on CCW site
- Deutsch (German) - but it’s not used by CCW site (see below)
- العربية (Arabic) - but it’s not mentioned by CCW site

On CCW Site we have:
- Brazilian Portuguese - uses an AWS link, not a link to an official translation
- Catalan - links to source code, not the projects site
- Dutch - uses an AWS link,  not a link to an official translation
- German - uses an AWS link, not a link to an official translation
- Ukranian - uses an AWS link, not a link to official translation

**Comment by martinpeck** [comment]
Suggest:

1. Fix CCW.org to point at official German materials and stop using the AWS link
1. Add Vietnamese, Russian and Arabic to the CCW.org site
1. Remove Catalan as the link doesn't take you to actual materials (it's the raw .md files)
1. Leave the other AWS links (Brazillian, Ukranian, Dutch)

**Comment by martinpeck** [comment]
Suggestion 1: agreed
Suggestion 2: agreed
Suggestion 3: decided to "do nothing" and leave Catalan links as-is
Suggestion 4: agreed

**Comment by martinpeck** [comment]
@freyjaodds to give me links to countries associated with Vietnamese, Russian and Arabic.

**Comment by freyjaodds** [comment]
We have to do nothing about this for now, I will supply links later on as we establish a relationship with these countries/regions.

**Comment by martinpeck** [comment]
469 days later...fixed and closed.
